blackCoffee-capstone/blackCoffee_server

- package-lock.json
- package.json
- src/database/database.config.ts
- src/database/seeds/users.seed.ts
- src/decorators/roles.decorator.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/guards/role.guard.ts
- src/modules/auth/strategies/facebook-auth.strategy.ts
- src/modules/auth/strategies/jwt-refresh.strategy.ts
- src/modules/auth/strategies/jwt.strategy.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.docs.ts
typeorm-seeding 을 사용해서 user table에 admin type의 관리자 데이터를 넣도록 구현했습니다.
현재 seed 데이터는 임시이고, 추후에 정식 개발자 계정을 만들어 업데이트하려 합니다.
개발자 전용 api를 구현하기 위해 RolesGuard를 생성했습니다.
- **database.config.ts 생성** : seed data를 넣기 위해 구현.
- **users.seed.ts 생성**
- **버전 충돌 해결** : typeorm 버전(0.3.x)과 typeorm-seeding 버전의 충돌 때문에 앞으로 패키지 설치 명령어는 **npm i --force**로 진행해주세요
- **roles decorator 생성** : 사용자와 관리자를 token으로 구분.
- **roles guard 생성** : 사용자와 관리자를 token으로 구분하여 특정 api에는 해당 role의 user만 접근 가능.
_(관리자 api 생성할 때, 제가 작성한 코드 참고해주세요)_
- `npm run seed:run && npm run start:dev`
작업이 급하게 이루어져서 이전 pr은 머지되었다 가정하고 작성했습니다. 코드리뷰 후 정식으로 머지되면 conflict 해결해서 푸쉬할게요
> Feat: Create seed admin user data & RolesGuard

- src/database/seeds/users.seed.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.docs.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/dto/login-request.dto.ts
- src/modules/auth/dto/login-response.dto.ts
- src/modules/auth/guards/local-auth.guard.ts
- src/modules/auth/strategies/local.strategy.ts
- **일반 회원가입 사용자와 관리자의 로그인 기능**을 구현했습니다.
- 클라이언트에게서 {email, password}를 받으면, LocalGuard를 통해 사용자 검증을 하고 Jwt-token을 생성해 반환하도록 구현했습니다.
- **local-auth.guard.ts 생성**
- **local.strategy.ts 생성**
- **vaildationEmailPassword Func 생성** : 이메일, 패스워드 검증
- **(Fix) admin user seed data** : password 해싱
> Feat: Login normal & admin user api (LocalGuard)

- src/public/css/admin-main.css
- src/public/js/admin-main.js
- src/views/admin-main.hbs
- src/views/view.controller.ts
> ### 작업 개요
> 관리자 메인 페이지의 전체적인 UI를 디자인하였습니다.
>> ### 기능
>> * 기본 UI 디자인
>> * 좌측 아코디언 스타일 메뉴 구현
>> * 버튼, 메뉴 hover 시 색상 변경
>> * 메인의 표 부분은 5~6개 정도만 보이도록 할 예정이고 메인 페이지에서 바로 승인하는 게 아닌 페이지로 이동하게 할 예정입니다.
>> * 데이터 부분은 어떤 형식으로 보일 지 나타내기 위해서 임의로 넣었습니다.
>> ### 차후 추가 될 기능
>> * 좌측 서브 메뉴와 메인 페이지의 버튼 클릭 시 광고 관리, 신고 관리 페이지로 이동
>> * 로그인 후 해당 메인 페이지 나타날 수 있도록 구현 예정
>> * 색상이나 세부 디자인 등은 유동적으로 변할 수도 있습니다.
>> * 괜찮은 아이콘을 못찾아서... 아이콘 찾으면 우측 하단 유저와 광고 부분에 아이콘이 삽입될 수 있습니다.
>> ### 테스트
>> * 서버 실행 후, localhost:3000/view/admin 이동 후 해당 페이지가 잘 나타나는지 테스트 부탁드립니다.
>> * 상기한 기능이 정상 동작하는지 테스트 부탁드립니다.
>> ### UI 디자인 사진 첨부
>>  ![admin-main](https://user-images.githubusercontent.com/108920053/200636961-a2f55046-0be0-4417-81ec-da5577e44f7e.png)
> Feat: Design admin main page UI

- package.json
- src/config/config.constant.ts
- src/config/config.module.ts
- src/config/config.validation.ts
- src/modules/ad-forms/ad-forms.controller.spec.ts
- src/modules/ad-forms/ad-forms.service.spec.ts
- src/modules/ad-forms/ad-forms.service.ts
이미지 파일 저장을 위해 NCloud Object Storage를 사용했습니다.
api를 연동하여 bucket에 이미지 파일이 정상적으로 들어가게 했습니다.
- adForms/service.ts : Ncloud 연동 및 파일 업로드
- env 파일 업데이트 : Ncloud 관련 키 추가 (따로 슬랙에 공지하겠습니다)
```bash
── bucket
├── licences (광고 요청때 사업자등록증)
│   └── ...png
│   └── ...png
├── sns-posts (인스타그램 사진 - 아직 생성X)
│   └── ...png
│   └── ...png
└── ...
``` 
- POST /ad-forms 로 요청 보냈을 때,
- 사진이 정상적으로 s3에 들어갔는지
- DB에 저장된 사진 url로 들어갔을 때 사진이 잘 보이는지
테스트 부탁드려요
- 저는 Postman의 form-data로 테스트 했습니다.
> Feat: Ncloud S3 api (ad-forms license image)

- src/public/css/admin-login.css
- src/public/js/admin-login.js
- src/public/js/admin-main.js
- src/views/admin-login.hbs
- src/views/view.controller.ts
> ### 작업 개요
> 관리자 로그인 UI는 더 수정이 없을 것 같아 API 연동하였습니다.
>> ### 기능
>> * 로그인 API 호출
>> * 토큰 저장
>> * admin 계정만 로그인 할 수 있도록 설정
>> * 로그인 성공 후 관리자 메인 페이지로 이동
>> ### 테스트
>> * 서버 실행 후 localhost:3000/admin/login에 접속하신 후 관리자 시드 데이터 계정과 비밀번호로 로그인하시고 정상적으로 로그인되는 지 확인 부탁드립니다.
>> * 로그인 후 저장된 토큰이 console 창에 나타나는지 확인 부탁드립니다. (확인 후 관련 코드 삭제 예정)
>> * 올바르지 않은 이메일/비밀번호 입력 시 로그인 실패 창이 뜨는지 확인 부탁드립니다.
>> * 관리자 계정이 아닌 다른 타입의 계정이 있으시다면 해당 계정으로 로그인하시고 관리자 계정으로 로그인 하라는 경고 알림 창이 뜨는지 확인 부탁드립니다.
>> ### 차후 추가될 기능
>> * 관리자만 사용 가능한 페이지는 관리자 로그인한 사용자만 사용할 수 있도록 할 예정입니다. 현재는 개발 시 불편할 것 같아 아직 구현하지 않았습니다.
>> * 로그아웃 기능
> Feat: Link API calls from UI in admin login

- src/modules/auth-codes/auth-codes.controller.spec.ts
- src/modules/auth-codes/auth-codes.module.ts
- src/modules/auth-codes/auth-codes.service.spec.ts
- src/modules/auth-codes/auth-codes.service.ts
- src/modules/taste-spots/taste-spots.service.ts
- src/modules/users/users.controller.spec.ts
- src/modules/users/users.module.ts
- src/modules/users/users.service.spec.ts
- src/modules/users/users.service.ts
- auth-code, user service 파일에 예외처리를 추가했습니다.
- 회원가입 인증코드를 요청하는 email이 이미 회원의 email이라면 exception
- 사용자의 여행지 취향을 post할 때, tasteSpots 배열 속 spotId 중 존재하지 않는 spotId가 있다면 exception
> Feat: Throw Exception code (auth-code, user)

- src/public/css/ad-request.css
- src/public/js/ad-request.js
- src/views/ad-request.hbs
- src/views/admin-main.hbs
- src/views/view.controller.ts
> ### 작업 개요
> * 광고 요청을 확인할 수 있는 목록 테이블의 UI를 디자인하였습니다.
>> ### 기능
>> * 메인 홈에서 광고 관리 -> 요청 광고 확인 클릭 시 해당 페이지로 이동
>> * 좌측 고정 메뉴 상단 '지금, 여기' 글자 클릭 시 메인 페이지로 이동 (홈 메뉴 아이콘 추가 예정)
>> * 광고 요청 확인 가능한 동적 테이블 디자인
>> * 테이블 내용 입력 후 행을 추가할 수 있는 기능 구현 (동적 테이블 확인 및 많은 더미 데이터로 인한 코드 가독성이 저하될 것을 우려하여 임시로 넣은 기능, API link 후 삭제 예정)
>> * 테이블 내 detail 선택 시 모달 팝업 창 오픈 (상세 내용 기재 x), 외부 클릭 시 닫힘
>> * 테이블 내 delete 선택 시 해당 행 삭제
>> ### 구현 예정
>> * 요청 날짜 별, 상태 별 정렬
>> * API 호출 후 정상적인 데이터 받아온 후 페이징 처리
>> * 모달 팝업 내 상세 내용 구현
>> * 테이블의 상세 디자인은 바뀔 수 있습니다
>> ### 테스트
>> * 홈(localhost:3000/view/admin)에서 광고 관리, 요청 광고 확인 메뉴 클릭 시 해당 페이지로 이동 되는지 확인 부탁드립니다.
>> * 좌측 메뉴 상단의 지금 여기 글자 클릭 시 메인 페이지로 이동 되는지 확인 부탁드립니다.
>> * 추가적으로 행의 내용을 입력 후 정상적으로 테이블이 늘어나는지 확인 부탁드립니다.
>> * delete 클릭 후 정상적으로 행의 내용이 삭제되는지 확인 부탁드립니다.
>> * detail 클릭 후 모달 팝업 창이 …
> Feat: Design admin ad request table UI

- src/entities/users.entity.ts
- src/modules/auth-codes/auth-codes.controller.ts
- src/modules/auth-codes/auth-codes.docs.ts
- src/modules/auth-codes/auth-codes.service.ts
- src/modules/auth-codes/dto/auth-code-response.dto.ts
- src/modules/auth-codes/dto/verify-auth-code-response.dto.ts
- src/modules/auth/auth.controller.spec.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.docs.ts
- src/modules/auth/auth.service.spec.ts
- src/modules/auth/auth.service.ts
- src/modules/users/dto/change-pw-request.dto.ts
- src/modules/users/users.controller.spec.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.docs.ts
- src/modules/users/users.module.ts
- src/modules/users/users.service.spec.ts
- src/modules/users/users.service.ts
- src/types/ad-form.types.ts
- 사용자 비밀번호 찾기 api를 구현했습니다.
- 사용자 비밀번호 변경 api를 구현했습니다.
- auth-codes/find-pw : 비밀번호 찾기 시 인증 메일 발송
- auth-codes/find-pw/verify : 비밀번호 찾기 시 인증 코드 검증
- auth/find-pw : 임시 비밀번호 메일로 발급
- users/change-pw : 비밀번호 수정
- 인증메일이 발송되는지
- 인증코드로 검증이 되는지
- 임시 비밀번호를 발급받고, 그 비밀번호로 로그인이 가능한지
- 비밀번호 수정 후 로그인이 되는지 (소셜 유저인경우 에러, 비밀번호가 틀릴 경우 에러)
> Feat: Find & Change user's password API

- src/modules/spots/dto/detail-spot-response.dto.ts
- src/modules/spots/dto/search-response.dto.ts
- src/modules/spots/spots.service.ts
- test/mock/locations.mock.ts
- 여행지 상세정보, 검색 페이지 반환 목록에 location 추가했습니다.
- detail-spot-response.dto.ts, search-response.dto.ts
- 여행지 상세 페이지, 검색 목록에서 여행지마다 location 잘 나타나는지 확인
> Feat: Return additional location at spot response

- src/modules/spots/dto/detail-spot-request.dto.ts
- src/modules/spots/dto/detail-spot-response.dto.ts
- src/modules/spots/dto/neayby-facility-response.dto.ts
- src/modules/spots/dto/search-request.dto.ts
- src/modules/spots/spots.controller.spec.ts
- src/modules/spots/spots.docs.ts
- src/modules/spots/spots.module.ts
- src/modules/spots/spots.service.spec.ts
- src/modules/spots/spots.service.ts
여행지 필터링 중복 선택 및 전체 선택 가능하게 변경하였습니다.
여행지 상세 페이지에서 주변 시설이 나오도록 추가하였습니다.
- 위치 필터링, 테마 필터링 중복 선택 가능
- 위치 필터링 전체 선택 시 해당 위치 전체 반환
- 여행지 상세 페이지 sns post 좋아요 순 정렬
- 여행지 상세 페이지 접속 시 카카오 맵 api를 사용하여 주변 시설들 반환(음식점, 카페, 주차장)
- spot swagger 정리
- 필터링 중복 및 전체 선택 시 잘 나오는지 확인
- 여행지 상세 페이지 주변 시설 확인
- 주변 시설 내용을 이름, 주소, url, 거리, 카테고리로 반환했는데 적절한지
- 주변 시설을 한 페이지에 1~15 개 정도 반환 가능해서 15개로 설정했는데 너무 많은지(or 페이지가 필요할지 등)
- 카테고리를 맛집으로 설정해서 '음식점', '카페' 가 나오는데 다른 카테고리가 필요할지
논의 사항과 관련된 내용(반환 내용, 카테고리)은 아래 링크에서 확인 가능
(https://developers.kakao.com/docs/latest/ko/local/dev-guide#search-by-category)
> Feat: duplicate filtering spots and nearby facilities

- src/entities/post-comments.entity.ts
- src/entities/posts.entity.ts
- src/entities/users.entity.ts
- src/modules/posts/dto/get-posts-comments-response.dto.ts
- src/modules/posts/dto/get-posts-response.dto.ts
- src/modules/posts/dto/post-comments-request.dto.ts
- src/modules/posts/dto/post-comments-response.dto.ts
- src/modules/posts/dto/posts-request.dto.ts
- src/modules/posts/posts.controller.spec.ts
- src/modules/posts/posts.controller.ts
- src/modules/posts/posts.docs.ts
- src/modules/posts/posts.module.ts
- src/modules/posts/posts.service.spec.ts
- src/modules/posts/posts.service.ts
- src/modules/users/dto/comments-user-response.dto.ts
- test/mock/post-comments.mock.ts
- 커뮤니티 게시글의 댓글 관련 api를 구현했습니다.
- 댓글 생성 api
- 댓글 삭제 api
- 댓글 목록 api
- post-comment entity 생성
- comment api들
- 위에 명시한 api들 모두 테스트 부탁드려요.
- 더 추가되었으면 하는 응답 데이터들 있으면 말씀해주세요.
> Feat: Community's comment api

- src/database/database.config.ts
- src/database/seeds/locations.seed.ts
- src/entities/spots.entity.ts
- src/modules/spots/dto/save-request.dto.ts
- src/modules/spots/dto/search-response.dto.ts
- src/modules/spots/dto/spot-request.dto.ts
- src/modules/spots/spots.service.ts
- Locaiton Seed data 수정
- Spot entity에 address 추가
- ML에서 address 추가로 받아와서 spot에 저장
- spot search page에서 목록 받아올 때, location metro_name, local_name 대신에 adress로 수정
- location seed  잘 들어가는지 확인
- spot entity에 address 추가 되었는지 확인
- post로 spot넣을 때 잘 들어가지는 지 확인
- search spot에서 전체 목록 (id, name, address) 받아와지는 지 확인
> Feat: Create address of spots and modify location seed data

- src/app.module.ts
- src/entities/posts.entity.ts
- src/entities/report-posts.entity.ts
- src/entities/users.entity.ts
- src/modules/ad-forms/ad-forms.controller.ts
- src/modules/posts/dto/main-posts-response.dto.ts
- src/modules/posts/dto/report-posts-request.dto.ts
- src/modules/posts/dto/report-posts-response.dto.ts
- src/modules/posts/posts.controller.spec.ts
- src/modules/posts/posts.controller.ts
- src/modules/posts/posts.docs.ts
- src/modules/posts/posts.module.ts
- src/modules/posts/posts.service.spec.ts
- src/modules/posts/posts.service.ts
- src/modules/report-posts/dto/all-reports-request.dto.ts
- src/modules/report-posts/dto/reports-response.dto.ts
- src/modules/report-posts/dto/update-multi-reports-request.dto.ts
- src/modules/report-posts/dto/update-reports-request.dto.ts
- src/modules/report-posts/report-posts.controller.spec.ts
- src/modules/report-posts/report-posts.controller.ts
- src/modules/report-posts/report-posts.docs.ts
- src/modules/report-posts/report-posts.module.ts
- src/modules/report-posts/report-posts.service.spec.ts
- src/modules/report-posts/report-posts.service.ts
- src/modules/spots/spots.service.ts
- test/mock/report-posts.mock.ts
- 게시글 신고 관련 api를 구현했습니다.
- 게시글 신고하기 api (모든 유저)
- 신고목록 상태 필터링 정렬 api (default=최신순 정렬) (관리자)
- 신고 상태 수정하기 api (관리자)
- 신고 삭제 api (관리자)
- 관리자가 게시글 삭제 api (관리자)
- report-post entity 생성
- POST posts/:id/reports : 게시글 신고
- GET report-posts(?status=) : 신고목록 상태 필터링 정렬 (status 쿼리 안보내면 최신순 정렬)
- PATCH report-posts/:id : 신고 상태 수정
- DELETE report-posts/:id : 신고 삭제
- DELETE posts/:id : (기존에 있던 api), 게시글 작성자 뿐만 아니라 관리자도 스스로 판단 하에 삭제가 가능하도록 수정
- ## 테스트
- 위에 명시한 api들 모두 테스트 부탁드려요 (관리자, 일반회원 각각 테스트 부탁드려용 잘 막히는지 등등 ㅎㅎ)
> Feat: Report-post api

- docker-compose.dev.yml
- src/entities/ad-form.entity.ts
- src/entities/locations.entity.ts
- src/modules/ad-forms/ad-forms.service.ts
- src/modules/admins/admins.service.ts
- src/modules/admins/dto/get-ad-form.response.dto.ts
- src/modules/auth/auth.controller.spec.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.docs.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/dto/delete-user-request.dto.ts
- src/modules/auth/guards/facebook-auth.guard.ts
- src/modules/auth/strategies/facebook-auth.strategy.ts
- 광고 신청에서 locationId 제거
- 페이스북 로그인 api 수정
- 사용자 로그아웃 api
- 사용자 탈퇴 api
- 관리자 로그인 api
- docker port 번호 수정 (3000 -> 80) : HTTPS 설정 위해
- GET auth/facebook-login : 테스트용
- GET auth/facebook-callback : 테스트용 (동훈님 계정 있어야 작업할 수 있어 아직 구현안함)
- POST auth/facebook-login : 클라이언트에게서 code를 받아, 이를 facebook api에 전달해 사용자 정보 가져오기 & 로그인
- POST auth/admin-login : 관지라 로그인
- POST auth/logout : 로그아웃
- POST auth/resign : 회원탈퇴
- 사용자 로그아웃, 탈퇴, 관리자 로그인 api 테스트 (일반 사용자 제대로 막아지는지)
- 페이스북 로그인 부분은 아직 제대로 구현되어 있지 않아, 테스트가 불가 (추후에 수정 예정)
> Feat: Update facebook login login & Add logout, resign api

- src/modules/posts/dto/main-posts-request.dto.ts
- src/modules/posts/dto/main-posts-response.dto.ts
- src/modules/posts/posts.docs.ts
- src/modules/posts/posts.service.ts
- src/types/posts-sort.types.ts
- 커뮤니티 게시판 리스트 순서 추가하였습니다.
- 커뮤니티 게시판 조회순, 좋아요 순 정렬 추가하였습니다.
- 커뮤니티 게시판 순서가 잘 나타나는지 (필터링 했을 때도), 정렬이 잘 되는지 확인
> Feat: Posts sorting addition & posts list with order

- src/modules/admins/admins.service.ts
- src/modules/posts/dto/main-posts-response.dto.ts
- src/modules/posts/posts.service.ts
- src/modules/ranks/dto/ranking-list-response.dto.ts
- src/modules/ranks/dto/ranking-map-response.dto.ts
- src/modules/ranks/ranks.service.ts
- src/modules/spots/dto/detail-spot-response.dto.ts
- src/modules/spots/spots.service.ts
- post list, ranking list, spot list, spot detail 전부 location 대신에 address 반환하도록 수정하였습니다.
- location filtering, theme filtering 이슈 해결하였습니다.
- post/ranking/spot list, spot 상세페이지 address 확인
- spot, post, ad filtering 확인
> Fix: Location & theme filtering and return address instead of location

- src/public/css/ad.css
- src/public/js/ad-request.js
- src/public/js/ad.js
- src/public/js/admin-main.js
- src/views/ad-request.hbs
- src/views/ad.hbs
- src/views/admin-main.hbs
- src/views/view.controller.ts
> ### 작업개요
> * 광고 등록 및 수정 페이지 UI 디자인 후 각 API 연동했습니다.
>> ### 기능
>> * 광고 등록 모달 창에서 광고 등록 기능 (데이터 하나라도 비어있을 시, 잘못된 데이터 전송 시 경고 알람 창)
>> * 기존 테이블 기능 (이름순 정렬, 필터링, 페이지네이션 등)
>> * 각 row 클릭 시 해당하는 데이터 상세 창으로 팝업, 하단의 edit 클릭 시 광고 수정
>> * 수정 창에서 기존 데이터 placeholder로 보여줌
>> * 아무것도 입력하지 않을 시 데이터 전송하지 않고 입력한 값만 전송
>> * 하단의 delete 클릭 시 등록된 광고 삭제
>> ### 테스트
>> * 상기한 기능들 테스트 부탁드립니다
>> ### UI 디자인 사진
>> ![광고 등록](https://user-images.githubusercontent.com/108920053/205229132-520c2d8a-c938-44da-a267-8cdf547797b1.png)
>> ![광고 수정](https://user-images.githubusercontent.com/108920053/205229162-b2f352c7-3446-4074-9fd5-11e28347db2a.png)
> Feat: Design ad register and edit page & Link API

- src/modules/auth-codes/auth-codes.service.ts
- src/modules/ranks/ranks.service.ts
- 랭크 반환 시 prev/next 전부 계산해서 반환
- 이미 인증한 이메일인 경우 못하게 막음
- DB 기준 이전 데이터 요청 시 prev: null, next: 가장 예전 것
- 이후 데이터 요청 시 prev: 가장 최신 것, next: null
- 2022114, 2022121 데이터 있을 때, 사잇값 2022116 요청 시 그 양 옆 데이터 반환, prev: 2022114, next: 2022121
- 랭크 db 가 없을 시 null, null 반환
> Feat: Ranks return calculating both last week and this week

- src/modules/ranks/ranks.service.ts
> Fix: If rank is null do not insert

- src/modules/auth/auth.service.ts
- src/modules/recommendations/recommendations.service.ts
- ssh 500 에러 발생 시, 에러 무시하고 다음 로직 수행하게 수정
- 프론트와 비밀번호 형식을 맞추기 위해 유효성 검사 코드 수정
- 비밀번호 형식을 맞추기 위해 비밀번호 찾기에서 발급되는 임시 비밀번호 형식을 수정
- 프론트에서 추천 여행지 요청 시 500 에러 발생하는지 확인 부탁드립니다. (에러 발생하면 바로 말씀해주세요.)
- 임시 비밀번호가 수정된 형식대로 발급되는지 확인 부탁드립니다. (8~15자리 사이 숫자, 특수문자, 영어 1개 이상씩)
> Fix: Do not respond to errors when 500 Err (Recomm)

- src/modules/ranks/ranks.service.ts
- src/modules/recommendations/recommendations.service.ts
- src/modules/spots/spots.service.ts
- src/modules/users/users.service.ts
- sns post없는 spot은 검색, 마이페이지, 랭킹, 추천 spot 리스트에서 나타나지 않도록 수정
> Fix: Fix return spot with sns post to be retrieved

- src/modules/posts/posts.service.ts
- src/modules/ranks/ranks.service.ts
- src/modules/spots/dto/search-request.dto.ts
- src/modules/spots/spots.docs.ts
- src/modules/spots/spots.service.ts
- src/types/sort.types.ts
- spot 정렬: 이름순 없애고 조회순(View), 인기순(Wish), 랭크순(Rank)으로 정렬
- select count하고 나서 number 전환 형식 변경 -> COUNT (*)::int (spot, post, rank)
> Feat: Sort spots by view and popularity

- src/modules/ranks/ranks.service.ts
- src/modules/recommendations/recommendations.service.ts
- 중간 중간 데이터셋을 관리할 때마다 삭제되는 데이터 때문에 랭크 반환 시 이슈가 있었습니다.
- 이슈 해결을 위해 랭크 반환 때마다 1~20위의 데이터들 중 빠진 데이터가 있다면 rank db를 Update하는 기능을 추가했습니다.
- 이를 위해 ml에서 이번주 rank를 받아올 때 1~20까지만 받아오는 것이 아니라 모든 rank를 받아오는 것으로 정했습니다.
- 저번에 예은님이 임의로 1~20까지 부여하는 코드는 삭제했습니다.
- rank table에 1~마지막 순위(최소 30? 정도)까지 데이터를 넣어두고 1~20위 내의 데이터들 중 몇개를 삭제한 다음 get rank api 테스트 부탁드려요. 1~20위까지 잘 나오는지, rank db가 update 되었는지
> Fix: Fix rank issues after deleting db data

- src/modules/posts/posts.service.ts
- src/modules/spots/spots.service.ts
- 테마 필터링 시 중복 방지를 위해서 distinct 대신 subQuery를 사용하였습니다. (spots, posts)
> Fix: Add subquery where in theme ids (spots, posts)

- src/modules/spots/dto/ml-sns-request.dto.ts
- src/modules/spots/dto/ml-spot-sns-request.dto.ts
- src/modules/spots/spots.controller.ts
- src/modules/spots/spots.docs.ts
- src/modules/spots/spots.service.ts
- 모든 주차의 랭킹을 ml로부터 받기 위해 모든 sns게시글을 ml로 보내고 랭킹을 받는 기능을 추가했습니다.
- 기존에 있던 POST /spots api에 추가할 예정입니다.
- 추후 작업 예정 : 예은님이 ml로부터 받은 데이터를 rank table에 update & insert 하는 기능 추가
> Feat: Add Send all snspost to ML func

- src/modules/ranks/dto/ranking-list-response.dto.ts
- src/modules/ranks/ranks.controller.spec.ts
- src/modules/ranks/ranks.controller.ts
- src/modules/ranks/ranks.docs.ts
- src/modules/ranks/ranks.module.ts
- src/modules/ranks/ranks.service.ts
- src/modules/spots/spots.docs.ts
- 랭킹 리스트에서 header를 받아서 isWish를 추가하는 작업하였습니다.
- isWish 여부
- ranking list에서 찜한 사용자 일 때, 아닐 때 반환 값 확인
> Feat: Return iswish when the user steamed in the ranking

- src/modules/ranks/dto/ranks-update-request.dto.ts
- src/modules/ranks/ranks.service.ts
- src/modules/spots/spots.service.ts
- ml서버에서 받은 JSON으로 전체 주차 모두 최대 50개까지 Rank Table에 Delete 및 Save 하는 로직으로 변경하였습니다.
> Feat: Update overall week ranking

- src/modules/posts/posts.service.ts
- src/modules/spots/spots.service.ts
- Spot, Post 검색하는 조건을 포괄적으로 변경하였습니다.
1. 대소문자 관계없이 영어 이름 검색 가능하도록 변경
2. 공백 상관없이 검색 가능하도록 변경
> Feat: Change english name search to be possible regardless of case

- src/modules/spots/spots.service.ts
- photourl 업데이트 시 빈배열의 Id를 삭제할 때 에러가 있어 수정했습니다.
> Fix: Fix update sns post photo-url api
