package.json
src/database/seeds/users.seed.ts
src/modules/auth/hash-password.ts

- docker 실행 때 bcrypt 버전 오류가 있어 bcryptjs로 수정했습니다.

Fix: bcrypt -> bcryptjs (docker err)

---

src/entities/auth-code.entity.ts
src/modules/auth-codes/auth-codes.service.ts
src/modules/auth/auth.controller.spec.ts
src/modules/auth/auth.module.ts
src/modules/auth/auth.service.spec.ts
src/modules/auth/auth.service.ts
src/types/auth-code.types.ts

- 이메일 인증을 하지 않은 사용자인 경우 회원가입을 막도록 signup func을 수정했습니다.
- 이메일 인증을 안했을 때 회원가입이 제대로 막히는지 테스트 부탁드려요.

Feat: Block notVarifyEmail user's signup

---

src/modules/spots/spots.service.ts

Fix: Fix empty array save error

---

src/modules/spots/dto/detail-spot-response.dto.ts

- 여행지 상세 페이지 geom을 latitude & longitude 반환으로 수정하였습니다.

Chore: Change detail spot response geom to latitude & longitude

---

src/database/database.config.ts
src/database/seeds/ranks.seed.ts
src/modules/ranks/dto/ranking-request.dto.ts
src/modules/ranks/dto/ranks-record-request.dto.ts
src/modules/spots/dto/search-page-response.dto.ts
src/modules/spots/spots.service.ts

- rank dto example 수정
- 검색 페이지 반환 결과에 총 페이지 수 추가
- rank seed data 추가

Feat: Calculate search page total page number & Seeding rank data

---

src/modules/posts/dto/main-posts-page-response.dto.ts
src/modules/posts/dto/main-posts-request.dto.ts
src/modules/posts/dto/main-posts-response.dto.ts
src/modules/posts/posts.controller.spec.ts
src/modules/posts/posts.controller.ts
src/modules/posts/posts.docs.ts
src/modules/posts/posts.service.spec.ts
src/modules/posts/posts.service.ts
src/types/posts-sort.types.ts

- GET (/posts) 위치 필터링, 테마 필터링, 제목 검색, 최신순 정렬

Feat: Community main search (filtering, sorting, search)

---

src/public/css/ad-request.css
src/public/js/ad-form.json
src/public/js/ad-request.js
src/public/js/admin-login.js
src/views/ad-request.hbs
src/views/admin-main.hbs
src/views/view.controller.ts

> ### 작업 개요
> * json 더미 데이터를 테이블로 받아오고, 해당하는 row 클릭 시 팝업되는 모달 창 내 상세 정보를 보여주는 ui를 작업했습니다.
>> ### 기능
>> * DETAIL이나 row 클릭 시 해당하는 row의 데이터를 모달 창에 띄워줍니다.
>> * 상태 변경이 가능한 approve, reject 버튼을 모달 창 하단에 추가했습니다.
>> * 차후 필터링이 가능하게 할 라디오 버튼을 테이블 상단에 추가했습니다.
>> ### 구현 예정
>> * 실제 데이터 받아오면 메인 페이지 테이블 수정 예정
>> * approve, reject api 연동
>> * 라디오 버튼 필터링 연동
>> * 데이터 변경 시마다 실시간으로 테이블 업데이트
>> ### 테스트
>> * DETAIL이나 row 클릭 시 상세 데이터가 모달 창에 잘 나타나는지 테스트 부탁드립니다.
>> * 모달 창 외부 (투명도 적용된 부분) 클릭 시 모달 창이 정상적으로 닫히는지 테스트 부탁드립니다.
>> * 각 row마다 데이터가 다른 지 테스트 부탁드립니다. (이름과 회사명만 다름)
>> ### UI 디자인 사진
>> ![ad-form-detail](https://user-images.githubusercontent.com/108920053/204100348-64444bea-8d3b-4681-85a8-d380344e13e9.png)

Feat: Get json data & Add add detail form

---

src/modules/spots/dto/spots-json.dto.ts
src/modules/spots/spots.service.ts

csv 파일(크롤링) -> ml -> 여행지 반환
csv 파일(크롤링) -> json으로 수정 -> kakao map api 사용하여 위도,경도 추출 -> ml -> 여행지 반환

Feat: Add latitude, longitude after modifying to csv file json

---

src/public/css/ad-request.css
src/public/css/admin-main.css
src/public/css/forbidden.css
src/public/js/ad-request.js
src/public/js/admin-login.js
src/public/js/admin-main.js
src/views/ad-request.hbs
src/views/admin-main.hbs
src/views/forbidden.hbs
src/views/view.controller.ts

> ### 작업 개요
> * 로그인, 로그아웃, 광고 요청 API를 연동하고 관리자가 아닌 계정을 제한하는 기능을 추가했습니다.
>> ### 기능
>> * 관리자가 아닐 시 경고 알림 창과 함께 강제로 로그인 페이지로 이동
>> * 이미 로그인 한 관리자일 경우 로그인 페이지 접속 시 강제로 메인 페이지로 이동
>> * 로그아웃 기능 (로그아웃 후 강제로 로그인 페이지 이동)
>> * 요청 광고 확인 (ad-form) API 연동
>> * 메인 페이지 요청 광고 확인 테이블 구현
>> ### 구현 예정
>> * 새로 고침 없이 실시간으로 테이블 업데이트 기능 (현재는 모달 창 닫을 때마다 새로고침)
>> ### 테스트
>> * /admin or /admin/ad-request 페이지 접속 시 (로그아웃 상태) 정상적으로 경고 알림 창이 뜨는지 확인 부탁드립니다.
>> * /login 에서 로그인 후 정상적으로 로그인이 되는지 확인 부탁드립니다.
>> * 로그인 상태에서 /login 접속 후 이미 로그인한 계정이라는 알림 창이 뜨는지 확인 부탁드립니다.
>> * 메인 페이지에서 요청 광고 확인 테이블 부분에 정상적으로 데이터가 불러와지는지 확인 부탁드립니다.
>> * 요청 광고 확인 페이지 접속 후 데이터 테이블이 정상적으로 불러와지는지 확인 부탁드립니다.
>> * 데이터 테이블의 각 row 클릭 시 모달 창이 정상적으로 뜨는지, 모달 창에 해당 row의 데이터가 정상적으로 불러와지는지 확인 부탁드립니다.
>> * 각 상태 변경 (approve, reject, todo) 시 정상적으로 변경되는지 (페이지, …

Feat: Link API & Restrict Permission

---

src/public/css/ad-request.css
src/public/js/ad-request.js
src/views/ad-request.hbs

> ### 작업 개요
> * 테이블에 데이터가 없을 때에도 모달 창이 열리는 버그 수정했습니다
>> ### 기능
>> * 테이블에 데이터 없을 때 모달 창이 열리지 않게 exception 추가
>> * 모달 창 외부를 클릭하지 않고 모달 창 내의 'X' 버튼 클릭 시 창이 닫히는 기능 추가
>> ### 테스트
>> * 상기한 기능들 테스트 부탁드립니다

Fix: Modal failure to open when no table

---

src/modules/ranks/dto/ranking-request.dto.ts
src/modules/ranks/dto/ranking-response.dto.ts
src/modules/ranks/ranks.docs.ts
src/modules/ranks/ranks.service.ts

- 랭크 List/Map 반환할 때 이전 페이지/다음 페이지 같이 반환하도록 수정했습니다
- 랭크 날짜-주차 계산하는거 수정했습니다
- 랭크 List/Map 반환 확인
- 랭크 날짜-주차 계산 잘 되는지 확인

Feat: Update date week with previous & next week

---

src/modules/recommendations/recommendations.service.ts

Feat: Add exception code to recommendation when no taste themes

---

src/modules/auth/auth.controller.ts
src/modules/auth/auth.docs.ts
src/modules/auth/auth.service.ts

- 클라이언트에게서 accessToken 대신 code를 받아 카카오 로그인을 진행하도록 수정했습니다.

Fix: Modify kakao login logic (accesstoken->code)

---

.gitignore
src/modules/auth/auth.controller.ts
src/modules/auth/auth.docs.ts
src/modules/auth/dto/kakao-login-request.dto.ts
src/modules/spots/spots.controller.ts
src/modules/spots/spots.docs.ts
src/modules/spots/spots.service.ts

- kakao login api 수정했습니다.
- body(code)
- 테스트를 위해 snsPost의 url을 모두 뽑아 test.txt파일에 저장하는 api를 생성했습니다.

Feat: Update sns photo

---

src/public/css/ad-request.css
src/public/css/ad.css
src/public/css/admin-main.css
src/public/css/posts-report.css
src/public/js/ad-request.js
src/public/js/ad.js
src/public/js/admin-login.js
src/public/js/admin-main.js
src/public/js/community-posts.js
src/public/js/posts-report.js
src/views/ad-request.hbs
src/views/ad.hbs
src/views/admin-main.hbs
src/views/posts-report.hbs

> ### 작업 개요
> * 로그인 시 엔터를 입력해도 로그인이 이루어지도록 이벤트 추가하였습니다. 해당 계정이 admin 계정인지 확인해주는 API를 변경하였고, 홈페이지로 이동할 수 있는 아이콘을 우측 상단에 추가하였습니다. 또한 access token이 만료되었을 때 refresh token으로 access token 재발급 할 수 있게 하였습니다.
>> ### 기능
>> * 로그인 시 마우스 클릭이 아닌 엔터를 입력해도 로그인을 할 수 있도록 이벤트 추가
>> * 우측 상단에 홈페이지 아이콘 추가하여 메인 홈으로 이동할 수 있게 함
>> * refresh token으로 access token 재발급 기능 추가
>> * 해당 계정이 admin 계정인지 확인하는 API 변경
>> ### 테스트
>> * 상기한 기능 테스트 부탁드립니다.

Feat: Add enter event

---

test/mock/locations.mock.ts

> ### 작업 개요
> * conflict 해결하였습니다.

Fix: Fix conflict

---

src/modules/auth-codes/auth-codes.controller.spec.ts
test/mock/auth-codes.mock.ts

- auth-code module 테스트 코드를 작성했습니다.

Test: Add test code to auth-code module

---

src/public/css/ad.css
src/public/js/ad.js

> ### 작업 개요
> * 이미지 사이즈 조절되게 하였습니다.

Feat: Modify image size auto control

---

src/modules/ad-forms/ad-forms.controller.ts
src/modules/ad-forms/ad-forms.docs.ts
src/modules/posts/dto/posts-request.dto.ts

- form data가 요청데이터로 올 때 배열형식을 string으로 수정했습니다.
- 기존
- / data='1'
- / data='2'
- 수정 후
- data='1,2'
- 광고요청의 파일 확장자 수정 (모두 가능)

Feat: Change form data

---

src/modules/posts/dto/main-posts-response.dto.ts
src/modules/posts/posts.controller.spec.ts
src/modules/posts/posts.service.ts
src/modules/users/users.controller.spec.ts
test/mock/click-posts.mock.ts
test/mock/locations.mock.ts
test/mock/postThemes.mock.ts
test/mock/posts.mock.ts

- posts module 테스트 코드 작업 (Create, Update, Get)

Test: Add test code at posts parts (create, update, get)

---

src/modules/admins/admins.controller.spec.ts
src/modules/spots/spots.controller.spec.ts
test/mock/ads.mock.ts

> ### 작업 개요
> * spots test code exception 추가 및 admins test code 추가하고 수정했습니다.

Feat: Add test code

---

src/modules/auth/auth.docs.ts
src/modules/spots/spots.docs.ts

- swagger에 ApiBearerAuth 적용이 안된 부분이 있어 추가했습니다.

Docs: Add BearerAuth to swagger

---

src/modules/likes/likes.service.ts
src/modules/wishes/wishes.service.ts
test/mock/like-posts.mock.ts
test/mock/wish-spots.mock.ts

- user의 wish spot, like post 에서 limit & offset 을 take & skip으로 수정하였습니다.

Fix: Change limit & offset -> take & skip (wish spot, like post)

---

src/public/css/ad-request.css
src/public/css/ad.css

> ### 작업 개요
> * 사이즈가 큰 이미지를 등록할 때를 대비하여 이미지를 상대 비율로 자동으로 줄여지게 수정하였습니다.

Feat: Modify ad and adform UI

---

src/app.module.ts
src/entities/ad.entity.ts
src/modules/admins/admins.controller.spec.ts
src/modules/admins/admins.service.ts
src/modules/admins/dto/ads-response.dto.ts
src/modules/admins/dto/get-ad-response.dto.ts
src/modules/ads/ads.controller.spec.ts
src/modules/ads/ads.controller.ts
src/modules/ads/ads.module.ts
src/modules/ads/ads.service.ts
test/mock/ads.mock.ts

- ads module 생성하였습니다.
- admin Get admin/ads, Get admin/adsAll 호출할 때 click 추가 되었습니다.
- 수민님이 광고 클릭 시 ad의 click count 증가하도록 api 추가 예정

Feat: Add click to ad entity & admin ad page (Get)

---

src/modules/ranks/ranks.service.ts
src/modules/spots/spots.service.ts

- rank update시 spot의 rank도 전부 업데이트 되도록 추가 작업
- test-ml 실행해서 spot - rank 업데이트 잘되는지 확인

Feat: Add spot rank to be updated

---

src/modules/ads/ads.controller.spec.ts

- Ad module에서 click api의 테스트 코드 작성하였습니다.

Test: Add test code from ad click api
